import Link from 'next/link';
const races=[['The Mammoth 200','mammoth-200'],['Hardrock 100','hardrock-100'],['Western States','western-states'],['UTMB','utmb'],['Wasatch 100','wasatch-100'],['The Bear','the-bear'],['Cascade Crest','cascade-crest'],['High Lonesome','high-lonesome'],['Run Rabbit Run','run-rabbit-run'],['Transgrancanaria','transgrancanaria'],['Canyons 100K','canyons-100k'],['Miwok 100K','miwok-100k'],['San Juan Solstice 50','san-juan-solstice-50'],['Scout Mountain Ultras','scout-mountain-ultras']];
export default function Home(){return <>
<section className="hero"><div className="hero-copy"><span className="eyebrow">Mountain Race Mentorship</span><h1>A Problem Shared,<br/><em>is a problem halved.</em></h1><p className="lede">Race-specific guidance for runners preparing to move through the mountains with confidence, clarity, and intention.</p><div style={{marginTop:30}}><Link className="button copper" href="https://calendly.com/jelam26-2/jimmywayne">Reserve a Session</Link></div></div><div className="hero-image"/></section>
<section className="section"><div className="intro"><div><span className="label">The idea</span><h2 className="display">Every race has its own personality.</h2></div><div className="body-large"><p>The best advice isn't always found in a training plan. It comes from knowing the course, understanding the terrain, anticipating the hard sections, and learning from someone who's already been there.</p><p>Jimmy Wayne offers 90-minute, race-specific mentorship sessions for mountain ultras he has personally completed. Ask anything. Course beta, pacing, gear, crew, weather, logistics, tactics—or the things you don't know to ask yet.</p></div></div></section>
<section className="section fog"><span className="label">Races</span><h2 className="display">Prepare for the race,<br/>not just the distance.</h2><div className="race-grid">{races.map(([name,slug])=><Link className="race-card" key={slug} href={'/races/'+slug}><div><span className="label">Mentorship</span><h3>{name}</h3></div><span className="arrow">Explore race →</span></Link>)}</div></section>
<section className="section dark"><div className="service"><div><span className="label">Race Mentorship Session</span><h2 className="display">Ninety minutes.<br/>Your questions.</h2><div className="price">$125</div><p>One focused conversation over Google Meet, followed by a personalized PDF summary with the key takeaways from your session.</p><Link className="button copper" href="https://calendly.com/jelam26-2/jimmywayne">Reserve Your Session</Link></div><div className="includes"><div>90-minute Google Meet</div><div>Course and terrain strategy</div><div>Pacing, tactics & cutoffs</div><div>Gear, fueling & weather</div><div>Crew, pacer & drop-bag strategy</div><div>Personalized follow-up PDF</div></div></div></section>
<section className="split-image"><div className="image-panel one"/><div className="image-panel two"/></section>
<section className="section"><div className="quote">“The mountains don't need to be conquered. They need to be understood.”</div><div style={{marginTop:45}}><Link className="button" href="/about">Meet Jimmy Wayne</Link></div></section>
</>}
