import Link from 'next/link';
import { notFound } from 'next/navigation';
const races: Record<string,{name:string; kicker:string; image:string; intro:string}>={
'mammoth-200':{name:'The Mammoth 200',kicker:'High country. Long nights. A different kind of endurance.',image:'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=2000&q=85',intro:'A 200-mile mountain race demands a different set of decisions. We can talk through the long view: terrain, sleep, pacing, gear, crew, and the moments where patience matters most.'},
'hardrock-100':{name:'Hardrock 100',kicker:'High altitude rewards patience.',image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2000&q=85',intro:'Hardrock is its own language. Use a mentorship session to understand the course, altitude, climbs, descents, weather, crew logistics, and the judgment required to get through 100 miles in the San Juans.'},
'western-states':{name:'Western States',kicker:'Heat, river crossings, and a long way to Auburn.',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=2000&q=85',intro:'Western States rewards a thoughtful first half and disciplined decisions later. We can build a race-day framework around heat, pacing, aid stations, terrain, and the realities of the canyons.'},
'utmb':{name:'UTMB',kicker:'One loop. Multiple countries. Endless decisions.',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2000&q=85',intro:'UTMB asks you to manage terrain, elevation, weather, crowds, travel, and a very long night. A session gives you room to ask the practical questions that a course map cannot answer.'},
'wasatch-100':{name:'Wasatch 100',kicker:'The Wasatch is more than a point-to-point course.',image:'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=2000&q=85',intro:'Wasatch has its own rhythm and its own traps. We can talk course flow, climbs, descents, aid stations, pacing, gear, weather, and how to make decisions when the race stops feeling simple.'},
'the-bear':{name:'The Bear',kicker:'Mountain running with a personality all its own.',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=2000&q=85',intro:'Bring your questions about the Bear and we will work through the course, terrain, pacing, gear, crew, and race-day strategy from a firsthand perspective.'},
'cascade-crest':{name:'Cascade Crest',kicker:'A course where knowing the terrain pays.',image:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=2000&q=85',intro:'Cascade Crest rewards runners who understand how the terrain changes the effort. We can break down the course, pacing, technical sections, gear, and logistics.'},
'high-lonesome':{name:'High Lonesome',kicker:'Big country. Small margins.',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=2000&q=85',intro:'High Lonesome is a mountain race where terrain and judgment matter. Bring the questions that are specific to your race and your goals.'},
'run-rabbit-run':{name:'Run Rabbit Run',kicker:'A fast hundred can still be a mountain hundred.',image:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=2000&q=85',intro:'Run Rabbit Run rewards a nuanced approach to pacing, terrain, and effort. We can talk through the course and the tactical decisions that shape the day.'},
'transgrancanaria':{name:'Transgrancanaria',kicker:'Island terrain. Long miles. A different race rhythm.',image:'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=2000&q=85',intro:'Transgrancanaria adds travel and unfamiliar terrain to the equation. Use a session to understand the course and build a practical race-day approach.'},
'canyons-100k':{name:'Canyons 100K',kicker:'Technical terrain and canyon heat.',image:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=2000&q=85',intro:'Canyons rewards runners who understand how the terrain changes throughout the day. We can discuss pacing, heat, climbs, descents, gear, and aid-station strategy.'},
'miwok-100k':{name:'Miwok 100K',kicker:'A beautiful course with plenty of ways to get it wrong.',image:'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=2000&q=85',intro:'Miwok is a course where details add up. Bring your questions about pacing, terrain, fueling, logistics, and the decisions that keep a good day moving.'},
'san-juan-solstice-50':{name:'San Juan Solstice 50',kicker:'High country in a shorter package.',image:'https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=2000&q=85',intro:'Fifty miles in the San Juans still demands respect for altitude and terrain. We can talk through how to approach the course with a clear plan.'},
'scout-mountain-ultras':{name:'Scout Mountain Ultras',kicker:'Mountain miles where preparation matters.',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=2000&q=85',intro:'Bring the questions you have about Scout Mountain. The session is yours: course beta, terrain, pacing, gear, logistics, crew, and race-day tactics.'}
};
export function generateStaticParams(){return Object.keys(races).map(slug=>({slug}));}
export default async function RacePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const race=races[slug];if(!race)return notFound();return <><section className="race-hero" style={{backgroundImage:`linear-gradient(90deg,rgba(15,18,18,.68),rgba(15,18,18,.12)),url('${race.image}')`}}><div className="overlay"><span className="eyebrow">Race Mentorship</span><h1>{race.name}</h1><p className="quote">{race.kicker}</p></div></section><section className="race-content"><div><span className="label">The conversation</span><h2 className="display">Come with questions.<br/>Leave with a plan.</h2><p className="body-large">{race.intro}</p><p>These sessions are not training plans. They are 90 minutes dedicated to the race you are preparing to run and the details that matter to you.</p><Link className="button copper" href="/reserve">Reserve a Session — $150</Link></div><div><span className="label">Topics we can cover</span><div className="topic-list"><div>Course & terrain beta</div><div>Pacing & effort</div><div>Gear & footwear</div><div>Fueling & hydration</div><div>Crew & pacer strategy</div><div>Weather & race conditions</div><div>Cutoffs & decision points</div><div>Race-week logistics</div></div></div></section></>}
